{% set name = "mkdocs-literate-nav" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c63d4385bb2b520baede25badad2d0936acebff3da175922c600d0a91902d8ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - mkdocs >=1.0.3

test:
  imports:
    - mkdocs_literate_nav

about:
  home: https://github.com/oprypin/mkdocs-literate-nav
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Plugin for MkDocs to specify the navigation in Markdown instead of YAML
  description: Plugin for MkDocs to specify the navigation in Markdown instead of YAML
  dev_url: https://github.com/oprypin/mkdocs-literate-nav

extra:
  recipe-maintainers:
    - cpcloud
