{% set name = "mkdocs-literate-nav" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 760e1708aa4be86af81a2b56e82c739d5a8388a0eab1517ecfd8e5aa40810a75

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - mkdocs >=1.4.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - mkdocs_literate_nav

about:
  home: https://github.com/oprypin/mkdocs-literate-nav
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Plugin for MkDocs to specify the navigation in Markdown instead of YAML
  description: Plugin for MkDocs to specify the navigation in Markdown instead of YAML
  dev_url: https://github.com/oprypin/mkdocs-literate-nav

extra:
  recipe-maintainers:
    - dhirschfeld
    - cpcloud
