{% set name = "mkdocs-literate-nav" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 78a7ab6d878371728acb0cdc6235c9b0ffc6e83c997b037f4a5c6ff7cef7d759

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - mkdocs >=1.0.3

test:
  imports:
    - mkdocs_literate_nav

about:
  home: https://github.com/oprypin/mkdocs-literate-nav
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Plugin for MkDocs to specify the navigation in Markdown instead of YAML
  description: Plugin for MkDocs to specify the navigation in Markdown instead of YAML
  dev_url: https://github.com/oprypin/mkdocs-literate-nav

extra:
  recipe-maintainers:
    - cpcloud
